import {
  type LucideIcon,
  Baby,
  Beer,
  BookHeart,
  ChartArea,
  Droplets,
  Earth,
  Heart,
  House,
  Landmark,
  Mountain,
  NotebookTabs,
  Palette,
  PiggyBank,
  Refrigerator,
  RotateCw,
  Shell,
  SplinePointer,
  Sun,
  TramFront,
  Trees,
  Globe,
  Camera,
  Music,
  Book,
  Code,
  Link,
  Star,
  Map,
  Compass,
  Calendar,
  Mail,
} from 'lucide-react'

const iconMap: Record<string, LucideIcon> = {
  heart: Heart,
  'notebook-tabs': NotebookTabs,
  palette: Palette,
  'spline-pointer': SplinePointer,
  sun: Sun,
  house: House,
  landmark: Landmark,
  mountain: Mountain,
  trees: Trees,
  'chart-area': ChartArea,
  shell: Shell,
  'rotate-cw': RotateCw,
  earth: Earth,
  baby: Baby,
  'piggy-bank': PiggyBank,
  beer: Beer,
  'tram-front': TramFront,
  'book-heart': BookHeart,
  refrigerator: Refrigerator,
  droplets: Droplets,
  globe: Globe,
  camera: Camera,
  music: Music,
  book: Book,
  code: Code,
  link: Link,
  star: Star,
  map: Map,
  compass: Compass,
  calendar: Calendar,
  mail: Mail,
}

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? Link
}

export { iconMap }
