#!/usr/bin/env bash
# Build and deploy the launch page to a remote server over SSH/rsync.
#
# Setup:
#   cp deploy.config.example.json deploy.config.json
#   cp .env.example .env   # set VITE_ADMIN_PASSWORD
#   npm run deploy
#
# Optional env overrides: DEPLOY_HOST, DEPLOY_USER, DEPLOY_PATH, DEPLOY_PORT, DEPLOY_SSH_KEY

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

SKIP_BUILD=0
DRY_RUN=0

for arg in "$@"; do
  case "$arg" in
    --skip-build) SKIP_BUILD=1 ;;
    --dry-run) DRY_RUN=1 ;;
    *) echo "Unknown option: $arg" >&2; exit 1 ;;
  esac
done

if [[ ! -f deploy.config.json ]]; then
  echo "Missing deploy.config.json. Copy deploy.config.example.json and edit it." >&2
  exit 1
fi

read_env() {
  local file="$1" key="$2"
  if [[ -f "$file" ]]; then
    grep -E "^${key}=" "$file" | head -n1 | cut -d= -f2- | tr -d "\"'" || true
  fi
}

HOST="${DEPLOY_HOST:-$(node -pe "require('./deploy.config.json').host")}"
USER="${DEPLOY_USER:-$(node -pe "require('./deploy.config.json').user")}"
REMOTE_PATH="${DEPLOY_PATH:-$(node -pe "require('./deploy.config.json').path")}"
PORT="${DEPLOY_PORT:-$(node -pe "require('./deploy.config.json').port || 22")}"
RELOAD_NGINX="${RELOAD_NGINX:-$(node -pe "String(require('./deploy.config.json').reloadNginx !== false)")}"
SSH_KEY="${DEPLOY_SSH_KEY:-$(node -pe "require('./deploy.config.json').sshKey || ''")}"

ADMIN_PASSWORD="$(read_env .env VITE_ADMIN_PASSWORD)"
if [[ -z "$ADMIN_PASSWORD" || "$ADMIN_PASSWORD" == "change-me-to-a-strong-password" ]]; then
  echo "Set a real VITE_ADMIN_PASSWORD in .env before deploying." >&2
  exit 1
fi

command -v rsync >/dev/null || { echo "rsync is required." >&2; exit 1; }
command -v ssh >/dev/null || { echo "ssh is required." >&2; exit 1; }

SSH_OPTS=(-p "$PORT")
RSYNC_SSH="ssh -p $PORT"
if [[ -n "$SSH_KEY" ]]; then
  SSH_OPTS+=(-i "$SSH_KEY")
  RSYNC_SSH="ssh -p $PORT -i $SSH_KEY"
fi

TARGET="${USER}@${HOST}"
echo "Deploy target: ${TARGET}:${REMOTE_PATH}"

if [[ "$SKIP_BUILD" -eq 0 ]]; then
  echo "Installing dependencies..."
  npm ci
  echo "Building production bundle..."
  export VITE_ADMIN_PASSWORD="$ADMIN_PASSWORD"
  npm run build
fi

if [[ ! -d dist ]]; then
  echo "dist/ not found. Run build first." >&2
  exit 1
fi

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "[dry-run] Would rsync dist/ to ${TARGET}:${REMOTE_PATH}"
  exit 0
fi

# Write publish API password config into the build output (not committed).
mkdir -p dist/api
php_password="${ADMIN_PASSWORD//\\/\\\\}"
php_password="${php_password//\'/\\\'}"
cat > dist/api/config.php <<EOF
<?php
// Generated by deploy.sh — do not commit.
return [
    'password' => '${php_password}',
];
EOF

# Keep live cards.json if the editor has already published.
if ssh "${SSH_OPTS[@]}" "$TARGET" "test -f '$REMOTE_PATH/data/cards.json'"; then
  echo "Preserving live data/cards.json on server"
  RSYNC_EXCLUDES=(--exclude 'data/cards.json')
else
  RSYNC_EXCLUDES=()
fi

echo "Uploading files..."
ssh "${SSH_OPTS[@]}" "$TARGET" "mkdir -p '$REMOTE_PATH'"
rsync -avz --delete "${RSYNC_EXCLUDES[@]}" -e "$RSYNC_SSH" dist/ "${TARGET}:${REMOTE_PATH}/"

# Ensure Apache can read uploaded assets on shared hosting.
echo "Fixing permissions..."
ssh "${SSH_OPTS[@]}" "$TARGET" "chmod 755 '$REMOTE_PATH/assets' '$REMOTE_PATH/data' '$REMOTE_PATH/api' 2>/dev/null; find '$REMOTE_PATH/assets' '$REMOTE_PATH/data' '$REMOTE_PATH/api' -type f -exec chmod 644 {} \; 2>/dev/null; chmod 644 '$REMOTE_PATH/index.html' '$REMOTE_PATH/.htaccess' '$REMOTE_PATH/robots.txt' '$REMOTE_PATH/_headers' 2>/dev/null; chmod 600 '$REMOTE_PATH/api/config.php' 2>/dev/null"

if [[ "$RELOAD_NGINX" == "true" ]]; then
  echo "Reloading nginx..."
  ssh "${SSH_OPTS[@]}" "$TARGET" "sudo nginx -t && sudo systemctl reload nginx"
fi

echo "Deploy complete."
