#Requires -Version 5.1
<#
.SYNOPSIS
  Build and deploy the launch page to a remote server over SSH/SCP.

.CONFIGURATION
  1. Copy deploy.config.example.json to deploy.config.json
  2. Copy .env.example to .env and set VITE_ADMIN_PASSWORD
  3. Run: npm run deploy

  Optional env overrides: DEPLOY_HOST, DEPLOY_USER, DEPLOY_PATH, DEPLOY_PORT, DEPLOY_SSH_KEY
#>
param(
    [switch]$SkipBuild,
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root

function Read-DotEnv {
    param([string]$Path)
    if (-not (Test-Path $Path)) { return @{} }
    $vars = @{}
    Get-Content $Path | ForEach-Object {
        $line = $_.Trim()
        if (-not $line -or $line.StartsWith('#')) { return }
        $eq = $line.IndexOf('=')
        if ($eq -lt 1) { return }
        $key = $line.Substring(0, $eq).Trim()
        $value = $line.Substring($eq + 1).Trim().Trim('"').Trim("'")
        $vars[$key] = $value
    }
    return $vars
}

function Require-Command {
    param([string]$Name)
    if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
        throw "Required command not found: $Name. Install OpenSSH client or add it to PATH."
    }
}

$configPath = Join-Path $Root 'deploy.config.json'
if (-not (Test-Path $configPath)) {
    throw "Missing deploy.config.json. Copy deploy.config.example.json and edit it."
}

$config = Get-Content $configPath -Raw | ConvertFrom-Json
$envFile = Read-DotEnv (Join-Path $Root '.env')

$hostName = if ($env:DEPLOY_HOST) { $env:DEPLOY_HOST } else { $config.host }
$user = if ($env:DEPLOY_USER) { $env:DEPLOY_USER } else { $config.user }
$remotePath = if ($env:DEPLOY_PATH) { $env:DEPLOY_PATH } else { $config.path }
$port = if ($env:DEPLOY_PORT) { $env:DEPLOY_PORT } else { $config.port }
$sshKey = if ($env:DEPLOY_SSH_KEY) { $env:DEPLOY_SSH_KEY } else { $config.sshKey }
$reloadNginx = if ($null -ne $config.reloadNginx) { [bool]$config.reloadNginx } else { $true }

if (-not $hostName -or -not $user -or -not $remotePath) {
    throw 'Deploy target incomplete. Set host, user, and path in deploy.config.json.'
}

$adminPassword = $envFile['VITE_ADMIN_PASSWORD']
if (-not $adminPassword -or $adminPassword -eq 'change-me-to-a-strong-password') {
    throw 'Set a real VITE_ADMIN_PASSWORD in .env before deploying.'
}

Require-Command ssh
Require-Command scp

$sshTarget = "${user}@${hostName}"
$sshArgs = @('-p', "$port")
$scpArgs = @('-P', "$port", '-r')
if ($sshKey) {
    $sshArgs += @('-i', $sshKey)
    $scpArgs += @('-i', $sshKey)
}

Write-Host "Deploy target: $sshTarget`:$remotePath"

if (-not $SkipBuild) {
    Write-Host 'Installing dependencies...'
    npm ci
    Write-Host 'Building production bundle...'
    $env:VITE_ADMIN_PASSWORD = $adminPassword
    npm run build
}

$dist = Join-Path $Root 'dist'
if (-not (Test-Path $dist)) {
    throw 'dist/ not found. Run build first.'
}

# Write publish API password config into the build output (not committed).
$apiDir = Join-Path $dist 'api'
if (-not (Test-Path $apiDir)) {
    New-Item -ItemType Directory -Path $apiDir | Out-Null
}
$phpPassword = $adminPassword.Replace('\', '\\').Replace("'", "\'")
$configPhp = @"
<?php
// Generated by deploy.ps1 — do not commit.
return [
    'password' => '$phpPassword',
];
"@
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText((Join-Path $apiDir 'config.php'), $configPhp, $utf8NoBom)

if ($DryRun) {
    Write-Host '[dry-run] Would upload dist/* to' $remotePath
    exit 0
}

# Keep live cards.json if the editor has already published.
$remoteCards = & ssh @sshArgs $sshTarget "if [ -f '$remotePath/data/cards.json' ]; then echo exists; fi"
$cardsFile = Join-Path $dist 'data\cards.json'
$preserveCards = $remoteCards -match 'exists'
if ($preserveCards -and (Test-Path $cardsFile)) {
    Write-Host 'Preserving live data/cards.json on server'
    Remove-Item $cardsFile -Force
}

Write-Host 'Uploading files...'
& ssh @sshArgs $sshTarget "mkdir -p '$remotePath'"
& scp @scpArgs (Join-Path $dist '*') "${sshTarget}:${remotePath}/"

# scp creates dirs as 700; Apache needs world-readable assets on shared hosting.
Write-Host 'Fixing permissions...'
& ssh @sshArgs $sshTarget "chmod 755 '$remotePath/assets' '$remotePath/data' '$remotePath/api' 2>/dev/null; find '$remotePath/assets' '$remotePath/data' '$remotePath/api' -type f -exec chmod 644 {} \; 2>/dev/null; chmod 644 '$remotePath/index.html' '$remotePath/.htaccess' '$remotePath/robots.txt' '$remotePath/_headers' 2>/dev/null; chmod 600 '$remotePath/api/config.php' 2>/dev/null"

if ($reloadNginx) {
    Write-Host 'Reloading nginx...'
    & ssh @sshArgs $sshTarget 'sudo nginx -t && sudo systemctl reload nginx'
}

Write-Host 'Deploy complete.'

